Add required node version to README
Adds a note for the required node version.

Otherwise you may see errors like this:

````shell
root@linux:/var/www/teamspeak-dynamic-banner/laravel# npm run build        
> build
> vite build

file:///var/www/teamspeak-dynamic-banner/laravel/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
npm ERR! code 1
npm ERR! path /var/www/teamspeak-dynamic-banner/laravel
npm ERR! command failed
npm ERR! command sh -c vite build

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-04-12T18_37_12_414Z-debug.log
````

````shell
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
1 info using npm@7.5.2
2 info using node@v12.22.12
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/share/nodejs/npm/npmrc Completed in 2ms
5 timing config:load:builtin Completed in 2ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/var/www/teamspeak-dynamic-banner/laravel/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/root/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 9ms
19 verbose npm-session b2951f100ca2cf28
20 timing npm:load Completed in 19ms
21 timing command:run-script Completed in 109ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/share/nodejs/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (events.js:314:20)
22 verbose stack     at maybeClose (internal/child_process.js:1022:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
23 verbose cwd /var/www/teamspeak-dynamic-banner/laravel
24 verbose Linux 5.10.0-21-amd64
25 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
26 verbose node v12.22.12
27 verbose npm  v7.5.2
28 error code 1
29 error path /var/www/teamspeak-dynamic-banner/laravel
30 error command failed
31 error command sh -c vite build
32 verbose exit 1
````